### ISSUE TITLE
Ports not set correctly

### ISSUE THREAD

**Issue by Berndinox** [bluedigits/iota-node#10]
```
2017-11-14 14:12:17 [main] DEBUG com.iota.iri.conf.Configuration - Setting UDP_RECEIVER_PORT with 14777
2017-11-14 14:12:17 [main] DEBUG com.iota.iri.conf.Configuration - Setting TCP_RECEIVER_PORT with 15777
```

```
version: '3'

services:
  iotanode:
    image: bluedigits/iota-node
    environment:
      - API_PORT=14265
      - UDP_PORT=14600
      - TCP_PORT=14600
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
      labels:
        - "traefik.port=14265"
        - "traefik.docker.network=proxy"
        - "traefik.frontend.rule=Host:offline.zone"
        - "traefik.backend=iotanode"
        - "traefik.frontend.entryPoints=http,https"
    #  replicas: 1
    networks:
      proxy:
        aliases:
          - iotanode
      default:
    volumes:
      - iotadat:/iri/data
      - /data/docker/iota/neighbors:/iri/conf/neighbors 
    ports:
      #- 14265:14265
      - 14600:14777
      #- 15600:15600



networks:
  proxy:
    external: true
  default:
    driver: overlay

volumes:
  iotadat:
    driver: local-persist
    driver_opts:
      mountpoint: /data/docker/iota
  #iotaconf:
  #  driver: local-persist
  #  driver_opts:
  #    mountpoint: /data/docker/iota/neighbors
```

also you should EXPOSE those Ports
