### ISSUE TITLE
FR - Curl

### ISSUE THREAD

**Issue by Berndinox** [bluedigits/iota-node#16]
Hy,

could we please add curl to the container.
First of all, to be able to add neighbors on the fly from within the Containert
The other Advantage is to be able to perform a healt check:

```
     healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost-api:PORT"]
        interval: 20s
        timeout: 10s
        retries: 3
```
